@host = http://127.0.0.1:6000/v1/dogs


### Get all dogs
GET {{host}}/?fields=name&offset=0&limit=2 HTTP/1.1


### Create new dogs
POST {{host}}/ HTTP/1.1
Content-Type: application/json

{
    "id": 0,
    "name": "Blackie5"
}


### Update dogs
PUT {{host}}/ HTTP/1.1
Content-Type: application/json

{
    "id": 19,
    "name": "Blackie"
}


### Delete dogs
DELETE {{host}}/ HTTP/1.1
Content-Type: application/json

[21,23,12,16,17]



### Get single dog
GET {{host}}/24?fields=id HTTP/1.1


### Update sing dog
PUT {{host}}/22 HTTP/1.1
Content-Type: application/json

{
  "id": 0, 
  "name": "Whitie"
}


### Delete single dog
DELETE {{host}}/22 HTTP/1.1
